"""empty message

Revision ID: 245c52fb2c73
Revises: 
Create Date: 2021-10-27 10:10:35.230616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '245c52fb2c73'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dungeons_first_adventure',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('txhash', sa.String(length=200), nullable=True),
    sa.Column('blocknum', sa.String(length=200), nullable=True),
    sa.Column('summoner_tokenid', sa.String(length=200), nullable=True),
    sa.Column('monster_tokenid', sa.String(length=200), nullable=True),
    sa.Column('summoner_class', sa.Integer(), nullable=True),
    sa.Column('copper_coins', sa.Integer(), nullable=True),
    sa.Column('is_summoner_win', sa.String(length=1), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('txhash')
    )
    op.create_table('dungeons_summoner_stat',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('summoner_tokenid', sa.String(length=200), nullable=True),
    sa.Column('summoner_class', sa.Integer(), nullable=True),
    sa.Column('copper_coins', sa.Integer(), nullable=True),
    sa.Column('wins_count', sa.Integer(), nullable=True),
    sa.Column('plays_count', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('summoner_tokenid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dungeons_summoner_stat')
    op.drop_table('dungeons_first_adventure')
    # ### end Alembic commands ###
