"""empty message

Revision ID: 3301dae66b10
Revises: 550d0ab4360c
Create Date: 2021-11-24 21:59:32.810959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3301dae66b10'
down_revision = '550d0ab4360c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('monster_nft_tracker', 'block_number',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.BigInteger(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('monster_nft_tracker', 'block_number',
               existing_type=sa.BigInteger(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###
