"""empty message

Revision ID: 41f91e07d401
Revises: 3ba077598747
Create Date: 2021-11-20 17:03:04.052612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41f91e07d401'
down_revision = '3ba077598747'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rarity_nft_tracker',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('block_number', sa.String(length=50), nullable=True),
    sa.Column('time_stamp', sa.String(length=50), nullable=True),
    sa.Column('txhash', sa.String(length=100), nullable=True),
    sa.Column('nonce', sa.String(length=50), nullable=True),
    sa.Column('block_hash', sa.String(length=100), nullable=True),
    sa.Column('from_address', sa.String(length=100), nullable=True),
    sa.Column('contract_address', sa.String(length=100), nullable=True),
    sa.Column('to_address', sa.String(length=100), nullable=True),
    sa.Column('token_id', sa.Integer(), nullable=True),
    sa.Column('token_name', sa.String(length=50), nullable=True),
    sa.Column('token_symbol', sa.String(length=50), nullable=True),
    sa.Column('transaction_index', sa.String(length=50), nullable=True),
    sa.Column('confirmations', sa.String(length=50), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('txhash')
    )
    op.create_table('rarity_nft_holder',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('holder_address', sa.String(length=100), nullable=True),
    sa.Column('token_id', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['token_id'], ['monster_list.token_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rarity_nft_holder')
    op.drop_table('rarity_nft_tracker')
    # ### end Alembic commands ###
