"""empty message

Revision ID: 7484e7b29336
Revises: 3301dae66b10
Create Date: 2021-11-24 22:12:01.582596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7484e7b29336'
down_revision = '3301dae66b10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dungeons_first_adventure', 'blocknum',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.BigInteger(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dungeons_first_adventure', 'blocknum',
               existing_type=sa.BigInteger(),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    # ### end Alembic commands ###
