"""empty message

Revision ID: 9b3e5901e440
Revises: d81b9b798528
Create Date: 2021-11-20 22:48:56.693984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b3e5901e440'
down_revision = 'd81b9b798528'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dungeons_first_adventure', sa.Column('called_from', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dungeons_first_adventure', 'called_from')
    # ### end Alembic commands ###
