"""empty message

Revision ID: adfe78f45450
Revises: b2a8cec3376f
Create Date: 2021-11-04 13:58:17.898209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adfe78f45450'
down_revision = 'b2a8cec3376f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monster_list',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('token_id', sa.Integer(), nullable=True),
    sa.Column('suffix', sa.Integer(), nullable=True),
    sa.Column('profession', sa.String(length=50), nullable=True),
    sa.Column('monster', sa.String(length=50), nullable=True),
    sa.Column('prefix', sa.String(length=50), nullable=True),
    sa.Column('token_uri', sa.String(length=2000), nullable=True),
    sa.Column('health_point', sa.Integer(), nullable=True),
    sa.Column('physical_damage_point', sa.Integer(), nullable=True),
    sa.Column('magical_damage_point', sa.Integer(), nullable=True),
    sa.Column('physical_defence', sa.Integer(), nullable=True),
    sa.Column('magical_defence', sa.Integer(), nullable=True),
    sa.Column('dodge', sa.Integer(), nullable=True),
    sa.Column('hit', sa.Integer(), nullable=True),
    sa.Column('critical', sa.Integer(), nullable=True),
    sa.Column('parry', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('monster_list')
    # ### end Alembic commands ###
