"""empty message

Revision ID: b2a8cec3376f
Revises: 02eee262ec16
Create Date: 2021-10-28 14:16:17.857543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2a8cec3376f'
down_revision = '02eee262ec16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dungeons_monster_coppers',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('monster_tokenid', sa.BigInteger(), nullable=True),
    sa.Column('monster', sa.String(length=50), nullable=True),
    sa.Column('prefix', sa.String(length=50), nullable=True),
    sa.Column('suffix', sa.Integer(), nullable=True),
    sa.Column('copper_coins', sa.BigInteger(), nullable=True),
    sa.Column('profession', sa.String(length=50), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('monster_tokenid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dungeons_monster_coppers')
    # ### end Alembic commands ###
