"""empty message

Revision ID: d81b9b798528
Revises: 41f91e07d401
Create Date: 2021-11-20 17:30:48.683135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd81b9b798528'
down_revision = '41f91e07d401'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('rarity_nft_holder_token_id_fkey', 'rarity_nft_holder', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('rarity_nft_holder_token_id_fkey', 'rarity_nft_holder', 'monster_list', ['token_id'], ['token_id'])
    # ### end Alembic commands ###
